### ISSUE TITLE
Widget tabs not displaying correctly

### ISSUE THREAD

**Issue by badsprad** [ubc/section-widget#7]
Widget tabs do not display in the Appearance > Widget page.

Steps to replicate:
1. go to Appearance > Widget
2. add the Section Widget to a sidebar
3. go to the sidebar & edit the widget content
4. widget displays full length of items, and is not tabbed

This could have something to do with jQuery version, although not 100% sure.

**Comment by badsprad** [comment]
I know why this is occurring now...

When the plugin is uploaded & installed in Wordpress, it is saved as the following:
wp-content/plugins/section-widget-master/

All of the PHP files reference the "base" URL as: section-widget, not section-widget-master.
Therefore, the files * do not load

* e.g.
section-widget-tabs.js

I tried renaming the zip file when downloaded from Github: from section-widget-master.zip to section-widget.zip - however, this does not help.

The only other thing I can think of, that has changed with this plugin, is the addition of the "node_modules" folder.

**Comment by richardtape** [comment]
Hi, when you download something from github, it appends the name of the branch. Simply rename the actual *folder* (not the zip file) after you've unzipped it, and you should be fine.

**Comment by badsprad** [comment]
Thanks Richard - this solves my issue!

Appreciated.
Brett
